// example/wujie/wujie-rf/src/componets/connect.jsx
import React, { useState } from "react";
import { Descriptions, Button, Input, Form } from "antd";
const { TextArea } = Input;

const menuSel = {
  1: "黄金糕",
  2: "双皮奶",
  3: "蚵仔煎",
};
const App = () => {
  const { userName, phoneNumber, adder, place, selVal } =
    window.$wujie.props.store;
  const [msg, setMsg] = useState("我是react子应用，我向主应用发送消息");
  const [descLsit] = useState([
    {
      key: "1",
      label: "用户名",
      children: userName,
    },
    {
      key: "2",
      label: "手机号",
      children: phoneNumber,
    },
    {
      key: "3",
      label: "居住地",
      children: adder,
    },
    {
      key: "4",
      label: "备注",
      children: menuSel[selVal],
    },
    {
      key: "5",
      label: "联系地址",
      span: 2,
      children: place,
    },
  ]);
  const sendMsg = () => {
    window.$wujie?.bus.$emit("main-alert-msg", msg);
  };
  return (
    <>
      <Descriptions title="react子应用通信测试" bordered items={descLsit} />
      <Form.Item label="编辑消息" style={{ marginTop: 20 }}>
        <TextArea
          rows={4}
          value={msg}
          onChange={(e) => {
            setMsg(e.target.value);
          }}
        />
      </Form.Item>
      <Button type="primary" onClick={sendMsg}>
        向主应用发送消息
      </Button>
    </>
  );
};
export default App;

// example/wujie/wujie-v3/src/components/connect.vue
<script setup>
import { ref } from "vue";
const menuSel = {
  "1":"黄金糕",
  "2":"双皮奶",
  "3":"蚵仔煎"
}
const desc = ref("我是vue3子应用，我向主应用发送的消息");
const listData = ref(window.$wujie.props.store);
const sendMsg = () => {
  window.$wujie?.bus.$emit("main-alert-msg", desc);
};
</script>

<template>
  <div>
    <h1>vue3子应用通信测试</h1>
    <el-descriptions
      title="主应用信息展示"
      :column="3"
      border
    >
      <el-descriptions-item label="用户名">
        {{ listData.userName }}
      </el-descriptions-item>
      <el-descriptions-item label="手机号">
        {{ listData.phoneNumber }}
      </el-descriptions-item>
      <el-descriptions-item label="居住地">
        {{ listData.adder }}
      </el-descriptions-item>
      <el-descriptions-item label="备注">
        {{ menuSel[listData.selVal] }}
      </el-descriptions-item>
      <el-descriptions-item
        label="联系地址"
        :contentStyle="{ 'text-align': 'right' }"
      >
        {{ listData.place }}
      </el-descriptions-item>
    </el-descriptions>
    <el-form-item label="编辑消息" style="margin-top: 20px">
      <el-input type="textarea" v-model="desc"></el-input>
    </el-form-item>
    <el-button type="primary" @click="sendMsg">向主应用发送消息</el-button>
  </div>
</template>

<style scoped></style>
