// example/wujie/wujie-rf/src/componets/isolation.jsx
import React from "react";
import { Col, Row } from "antd";
import styles from "./index.module.css";
export default function Home() {
  return (
    <div>
      <h3>react子应用</h3>
        <Row style={{ marginBottom: 10 }}>
          <Col span={12} className={styles.firstCol}>
            class="first-col"
            <br />
            background-color: blue;
            <br />
            font-size: 20px;
          </Col>
          <Col span={12} className={styles.secondCol}>
            class="second-col"
            <br />
            background-color: orange;
            <br />
            font-size: 20px;
          </Col>
        </Row>
    </div>
  )
}

// example/wujie/wujie-v3/src/components/isolation.vue
<script setup>

</script>

<template>
 <div>
    <el-col>
      <h3>vue3子应用</h3>
    </el-col>
  </div>
  <el-row>
    <el-col :span="12" class="first-col">class="first-col"<br />background-color: red;<br />font-size: 20px;</el-col>
    <el-col :span="12" class="second-col">class="second-col"<br />background-color: green;<br />font-size: 20px;</el-col>
  </el-row>
</template>

<style scoped>
.first-col {
  color: #ffffff;
  background-color: red;
  font-size: 20px;
}

.second-col {
  color: #ffffff;
  background-color: green;
  font-size: 20px;
}
</style>
